### PR TITLE
Updated to the latest version

### PR DESCRIPTION
**Pull request by phax**
Update for usage with the Spring 2021 rules valid per today

### CODE REVIEW

**Comment by eivinhb** [comment]
Oh, i'm sorry. I did not see that I made a conflict for you. Are you able to rebase your branch and fix the conflict? I'm preparing a first alpha release of this lib now.

**Comment by phax** [comment]
Let me check - 1 sec

**Comment by phax** [comment]
@eivinhb next try :)

**Comment by eivinhb** [comment]
@phax Thank you very much. 

First of all, I cant seem to be able to compile this code. 
`java.lang.NoClassDefFoundError: com/helger/phive/peppol/PeppolValidation3_12_0` Somehow the jars are not placed in the classpath.

Secondly: The `legacy` library. Is there a way we can avoid this? If you point me to some documentation on the changes to the api I can look into it.

**Comment by phax** [comment]
@eivinhb That change was introduced in the phive-rules 2.1.4, that PeppolValidation3_12_0 was added. Please check, that you updated your dependencies.

And regarding the legacy validations: well as long as you include the "third party validations" in your validation artefact registry, you need to have those. There are no current thirdparty validations atm that are not part of the Peppol validation artefacts directly.
Just drop the calls to "PeppolLegacyThirdpartyValidation" in your code (2 places) and you can get rid of the "legacy" library.

**Pull request merged**
